// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexico.jflex

package com.mycompany.practica1compi1;
import java_cup.runtime.*;



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\1\22\0\1\1\7\0"+
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\0\1\12"+
    "\12\13\7\0\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\23\1\26\1\27\1\30"+
    "\1\31\1\32\1\23\1\33\1\34\1\35\1\36\1\37"+
    "\3\23\1\40\4\0\1\41\1\0\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\23"+
    "\1\26\1\27\1\30\1\31\1\32\1\23\1\33\1\34"+
    "\1\35\1\36\1\37\3\23\1\40\12\0\1\3\252\0"+
    "\2\42\115\0\1\43\u01a8\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\22\14\1\0\2\14\1\0"+
    "\12\14\1\0\6\14\1\0\2\14\1\0\7\14\1\0"+
    "\4\14\1\0\1\15\1\16\4\14\1\0\2\14\1\0"+
    "\4\14\1\0\1\14\1\17\2\20\2\14\1\0\2\14"+
    "\1\0\1\14\1\0\2\14\1\21\1\0\1\14\1\0"+
    "\2\22\1\14\1\23\2\14\1\0\1\14\1\24\1\14"+
    "\1\0\1\25\1\14\1\0\1\25\1\14\1\0\2\14"+
    "\1\0\1\14\1\0\1\26\1\27\1\14\1\0\2\14"+
    "\1\0\1\14\1\0\2\30\1\31\1\14\1\31\1\14"+
    "\1\0\1\14\1\0\1\14\2\32\2\33\1\34\2\35"+
    "\2\36\2\14\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\44\0\44\0\44\0\44\0\44"+
    "\0\44\0\44\0\44\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c"+
    "\0\u0240\0\u0264\0\u0288\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\u033c"+
    "\0\u0360\0\u0384\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c"+
    "\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c"+
    "\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c"+
    "\0\u06c0\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774\0\u0798\0\u07bc"+
    "\0\u07e0\0\u0804\0\u0828\0\u084c\0\264\0\264\0\u0870\0\u0894"+
    "\0\u08b8\0\u08dc\0\u0900\0\u0924\0\u0948\0\u096c\0\u0990\0\u09b4"+
    "\0\u09d8\0\u09fc\0\u0a20\0\u0a44\0\264\0\264\0\44\0\u0a68"+
    "\0\u0a8c\0\u0ab0\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40\0\u0b64\0\u0b88"+
    "\0\u0bac\0\264\0\u0bd0\0\u0bf4\0\u0c18\0\264\0\44\0\u0c3c"+
    "\0\264\0\u0c60\0\u0c84\0\u0ca8\0\u0ccc\0\264\0\u0cf0\0\u0d14"+
    "\0\264\0\u0d38\0\u0d5c\0\44\0\u0d80\0\u0da4\0\u0dc8\0\u0dec"+
    "\0\u0e10\0\u0e34\0\u0e58\0\264\0\264\0\u0e7c\0\u0ea0\0\u0ec4"+
    "\0\u0ee8\0\u0f0c\0\u0f30\0\u0f54\0\264\0\44\0\264\0\u0f78"+
    "\0\44\0\u0f9c\0\u0fc0\0\u0fe4\0\u1008\0\u102c\0\264\0\44"+
    "\0\264\0\44\0\264\0\264\0\44\0\264\0\44\0\u1050"+
    "\0\u1074\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\3\16"+
    "\1\20\3\16\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\3\16\1\27\1\16\3\2\45\0\1\3\55\0\1\14"+
    "\43\0\14\16\1\30\1\31\7\16\1\32\1\16\15\0"+
    "\27\16\15\0\1\16\1\33\3\16\1\34\3\16\1\35"+
    "\11\16\1\36\3\16\1\37\14\0\20\16\1\40\6\16"+
    "\15\0\11\16\1\41\15\16\1\42\14\0\16\16\1\43"+
    "\10\16\15\0\5\16\1\44\21\16\15\0\2\16\1\45"+
    "\24\16\15\0\16\16\1\46\10\16\15\0\5\16\1\47"+
    "\10\16\1\50\10\16\15\0\5\16\1\51\21\16\15\0"+
    "\1\16\1\52\25\16\15\0\11\16\1\53\10\16\1\54"+
    "\4\16\1\55\14\0\23\16\1\56\3\16\15\0\6\16"+
    "\1\57\20\16\15\0\13\16\1\60\13\16\15\0\20\16"+
    "\1\61\6\16\15\0\1\16\1\62\16\16\1\63\6\16"+
    "\35\0\1\64\23\0\1\16\1\65\25\16\15\0\15\16"+
    "\1\66\11\16\32\0\1\67\26\0\20\16\1\70\6\16"+
    "\15\0\7\16\1\71\17\16\15\0\12\16\1\72\14\16"+
    "\15\0\13\16\1\73\13\16\15\0\3\16\1\74\23\16"+
    "\15\0\12\16\1\75\6\16\1\76\5\16\1\0\1\77"+
    "\13\0\20\16\1\100\6\16\15\0\20\16\1\101\6\16"+
    "\15\0\14\16\1\102\12\16\15\0\5\16\1\103\21\16"+
    "\31\0\1\104\27\0\13\16\1\105\13\16\15\0\5\16"+
    "\1\106\21\16\15\0\5\16\1\107\21\16\15\0\3\16"+
    "\1\110\23\16\15\0\4\16\1\111\22\16\15\0\24\16"+
    "\1\112\2\16\20\0\1\113\40\0\6\16\1\114\20\16"+
    "\15\0\5\16\1\115\21\16\22\0\1\116\36\0\1\16"+
    "\1\117\25\16\15\0\20\16\1\120\6\16\15\0\5\16"+
    "\1\121\21\16\15\0\11\16\1\122\15\16\1\123\14\0"+
    "\22\16\1\124\4\16\15\0\16\16\1\125\10\16\15\0"+
    "\1\16\1\126\25\16\16\0\1\127\42\0\4\16\1\130"+
    "\22\16\15\0\11\16\1\131\15\16\1\132\14\0\1\16"+
    "\1\133\25\16\15\0\20\16\1\134\6\16\16\0\1\135"+
    "\42\0\21\16\1\136\5\16\1\0\1\137\13\0\23\16"+
    "\1\140\3\16\15\0\20\16\1\141\6\16\15\0\1\16"+
    "\1\142\25\16\40\0\1\143\20\0\11\16\1\144\15\16"+
    "\1\145\14\0\1\16\1\146\25\16\16\0\1\147\42\0"+
    "\4\16\1\150\22\16\15\0\16\16\1\151\10\16\15\0"+
    "\22\16\1\152\4\16\15\0\7\16\1\153\17\16\24\0"+
    "\1\154\34\0\1\16\1\155\25\16\15\0\5\16\1\156"+
    "\21\16\15\0\13\16\1\157\13\16\30\0\1\160\30\0"+
    "\20\16\1\161\6\16\15\0\11\16\1\162\15\16\1\163"+
    "\34\0\1\164\23\0\22\16\1\165\4\16\37\0\1\166"+
    "\21\0\13\16\1\167\13\16\15\0\1\16\1\170\25\16"+
    "\30\0\1\171\30\0\3\16\1\172\23\16\20\0\1\173"+
    "\40\0\16\16\1\174\10\16\15\0\16\16\1\175\10\16"+
    "\15\0\16\16\1\176\10\16\33\0\1\177\25\0\15\16"+
    "\1\200\11\16\15\0\13\16\1\201\13\16\30\0\1\202"+
    "\30\0\16\16\1\203\10\16\33\0\1\204\25\0\5\16"+
    "\1\205\21\16\22\0\1\206\36\0\16\16\1\207\10\16"+
    "\15\0\4\16\1\210\22\16\33\0\1\211\25\0\1\16"+
    "\1\212\25\16\16\0\1\213\42\0\15\16\1\214\11\16"+
    "\32\0\1\215\26\0\7\16\1\216\17\16\15\0\16\16"+
    "\1\217\10\16\33\0\1\220\25\0\20\16\1\221\6\16"+
    "\35\0\1\222\23\0\16\16\1\223\10\16\15\0\20\16"+
    "\1\224\6\16\35\0\1\225\23\0\16\16\1\226\10\16"+
    "\33\0\1\227\25\0\23\16\1\230\3\16\15\0\13\16"+
    "\1\231\13\16\15\0\16\16\1\232\10\16\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4248];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\10\11\23\1\1\0\2\1\1\0"+
    "\12\1\1\0\6\1\1\0\2\1\1\0\7\1\1\0"+
    "\4\1\1\0\6\1\1\0\2\1\1\0\4\1\1\0"+
    "\3\1\1\11\2\1\1\0\2\1\1\0\1\1\1\0"+
    "\3\1\1\0\1\1\1\0\1\1\1\11\4\1\1\0"+
    "\3\1\1\0\2\1\1\0\1\11\1\1\1\0\2\1"+
    "\1\0\1\1\1\0\3\1\1\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\11\2\1\1\11\1\1\1\0\1\1"+
    "\1\0\2\1\1\11\1\1\1\11\2\1\1\11\1\1"+
    "\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      yyline = 1; 
    yychar = 1; 
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Este es un error lexico: "+yytext()+", en la linea: "
    + yyline + ", en la columna: "+yychar);
            }
            // fall through
          case 32: break;
          case 2:
            { 
            }
            // fall through
          case 33: break;
          case 3:
            { yychar=1;
            }
            // fall through
          case 34: break;
          case 4:
            { return new Symbol(sym.PARIZQ,yyline,(int)yychar, yytext());
            }
            // fall through
          case 35: break;
          case 5:
            { return new Symbol(sym.PARDER,yyline,(int)yychar, yytext());
            }
            // fall through
          case 36: break;
          case 6:
            { return new Symbol(sym.POR,yyline,(int)yychar, yytext());
            }
            // fall through
          case 37: break;
          case 7:
            { return new Symbol(sym.MAS,yyline,(int)yychar, yytext());
            }
            // fall through
          case 38: break;
          case 8:
            { return new Symbol(sym.COMA,yyline,(int)yychar, yytext());
            }
            // fall through
          case 39: break;
          case 9:
            { return new Symbol(sym.MENOS,yyline,(int)yychar, yytext());
            }
            // fall through
          case 40: break;
          case 10:
            { return new Symbol(sym.DIV,yyline,(int)yychar, yytext());
            }
            // fall through
          case 41: break;
          case 11:
            { return new Symbol(sym.ENTERO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 42: break;
          case 12:
            { return new Symbol(sym.ID,yyline,(int)yychar, yytext());
            }
            // fall through
          case 43: break;
          case 13:
            { return new Symbol(sym.AZUL,yyline,(int)yychar, yytext());
            }
            // fall through
          case 44: break;
          case 14:
            { return new Symbol(sym.CAFE,yyline,(int)yychar, yytext());
            }
            // fall through
          case 45: break;
          case 15:
            { return new Symbol(sym.ROJO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 46: break;
          case 16:
            { return new Symbol(sym.ROSA,yyline,(int)yychar, yytext());
            }
            // fall through
          case 47: break;
          case 17:
            { return new Symbol(sym.CURVA,yyline,(int)yychar, yytext());
            }
            // fall through
          case 48: break;
          case 18:
            { return new Symbol(sym.LINEA,yyline,(int)yychar, yytext());
            }
            // fall through
          case 49: break;
          case 19:
            { return new Symbol(sym.NEGRO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 50: break;
          case 20:
            { return new Symbol(sym.VERDE,yyline,(int)yychar, yytext());
            }
            // fall through
          case 51: break;
          case 21:
            { return new Symbol(sym.ANIMAR,yyline,(int)yychar, yytext());
            }
            // fall through
          case 52: break;
          case 22:
            { return new Symbol(sym.MORADO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 53: break;
          case 23:
            { return new Symbol(sym.OBJETO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 54: break;
          case 24:
            { return new Symbol(sym.CELESTE,yyline,(int)yychar, yytext());
            }
            // fall through
          case 55: break;
          case 25:
            { return new Symbol(sym.CIRCULO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 56: break;
          case 26:
            { return new Symbol(sym.AMARILLO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 57: break;
          case 27:
            { return new Symbol(sym.ANTERIOR,yyline,(int)yychar, yytext());
            }
            // fall through
          case 58: break;
          case 28:
            { return new Symbol(sym.CUADRADO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 59: break;
          case 29:
            { return new Symbol(sym.GRAFICAR,yyline,(int)yychar, yytext());
            }
            // fall through
          case 60: break;
          case 30:
            { return new Symbol(sym.POLIGONO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 61: break;
          case 31:
            { return new Symbol(sym.RECTANGULO,yyline,(int)yychar, yytext());
            }
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
