
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.practica1compi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 18;
  public static final int MENOS = 4;
  public static final int CURVA = 19;
  public static final int ANIMAR = 25;
  public static final int PARIZQ = 2;
  public static final int CAFE = 15;
  public static final int CUADRADO = 22;
  public static final int PARDER = 3;
  public static final int OBJETO = 26;
  public static final int VERDE = 12;
  public static final int ID = 29;
  public static final int POR = 6;
  public static final int ROJO = 10;
  public static final int GRAFICAR = 20;
  public static final int AMARILLO = 11;
  public static final int COMA = 8;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int MORADO = 14;
  public static final int CELESTE = 17;
  public static final int POLIGONO = 24;
  public static final int error = 1;
  public static final int CIRCULO = 21;
  public static final int AZUL = 9;
  public static final int ROSA = 16;
  public static final int ENTERO = 28;
  public static final int ANTERIOR = 27;
  public static final int NEGRO = 13;
  public static final int RECTANGULO = 23;
  public static final int MAS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARIZQ",
  "PARDER",
  "MENOS",
  "MAS",
  "POR",
  "DIV",
  "COMA",
  "AZUL",
  "ROJO",
  "AMARILLO",
  "VERDE",
  "NEGRO",
  "MORADO",
  "CAFE",
  "ROSA",
  "CELESTE",
  "LINEA",
  "CURVA",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "POLIGONO",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "ENTERO",
  "ID"
  };
}

